# Generated by Django 2.1.7 on 2019-04-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20190412_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpreference',
            name='mailchimp_msg',
            field=models.TextField(null=True),
        ),
    ]
