# Generated by Django 2.1.7 on 2019-04-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivation',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
